// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srbkundrmawpgwtuwtcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYmt1bmRybWF3cGd3dHV3dGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTYzNjMsImV4cCI6MjA2NjI3MjM2M30.FlIozOLn3LAQ1kzVs9epSgbBI5Sq2RgAeweqAGalV2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);